language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
gemfile:
  - gemfiles/rails3.2_protobuf.gemfile
  - gemfiles/rails3.2_ruby_protobuf.gemfile
  - gemfiles/rails4.0.0_protobuf.gemfile
  - gemfiles/rails4.0.0_ruby_protobuf.gemfile
  - gemfiles/rails4.1.0_protobuf.gemfile
  - gemfiles/rails4.1.0_ruby_protobuf.gemfile
  - gemfiles/rails4.2.0_protobuf.gemfile
  - gemfiles/rails4.2.0_ruby_protobuf.gemfile
matrix:
  include:
  - rvm: 2.3
    gemfile: gemfiles/rails5.0.1_protobuf.gemfile
  - rvm: 2.3
    gemfile: gemfiles/rails5.0.1_ruby_protobuf.gemfile
after_success:
  - bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 6bdbd657ebc3097c1ca86672a45b6408a457a5d80cea234937f4d4adfbf004bd
